//what does this file do? It defines and exports constants representing various academic departments, along with an array of their values for easy reference.
export const DEPARTMENTS = Object.freeze({
  COMPUTER_SCIENCE: "COMPUTER_SCIENCE",
  SOFTWARE_ENGINEERING: "SOFTWARE_ENGINEERING",
  INFORMATION_TECHNOLOGY: "INFORMATION_TECHNOLOGY",
  COMPUTER_ENGINEERING: "COMPUTER_ENGINEERING",
  DATA_SCIENCE: "DATA_SCIENCE",
  ARTIFICIAL_INTELLIGENCE: "ARTIFICIAL_INTELLIGENCE",
  CYBERSECURITY_INFOSEC: "CYBERSECURITY_INFOSEC",
  INFORMATION_SYSTEMS: "INFORMATION_SYSTEMS",
  BIOINFORMATICS: "BIOINFORMATICS",
});

export const DEPARTMENT_VALUES = Object.values(DEPARTMENTS);
