export const TEAM_JOIN_REQUEST_STATUSES = Object.freeze({
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
});

export const TEAM_JOIN_REQUEST_STATUS_VALUES = Object.values(TEAM_JOIN_REQUEST_STATUSES);
