export const TEAM_STAGES = Object.freeze({
  REQUIREMENTS: "REQUIREMENTS",
  DESIGN: "DESIGN",
  IMPLEMENTATION: "IMPLEMENTATION",
  TESTING: "TESTING",
  DEPLOYMENT: "DEPLOYMENT",
  MAINTENANCE: "MAINTENANCE",
});

export const TEAM_STAGE_VALUES = Object.values(TEAM_STAGES);
