export const TEAM_INVITATION_STATUSES = Object.freeze({
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
  EXPIRED: "EXPIRED",
});

export const TEAM_INVITATION_STATUS_VALUES = Object.values(TEAM_INVITATION_STATUSES);
