export const TEAM_SUPERVISOR_REQUEST_STATUSES = Object.freeze({
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
  CANCELLED: "CANCELLED",
});

export const TEAM_SUPERVISOR_REQUEST_STATUS_VALUES = Object.values(TEAM_SUPERVISOR_REQUEST_STATUSES);
