export const TRACKS = Object.freeze({
  FRONTEND_DEVELOPMENT: "FRONTEND_DEVELOPMENT",
  BACKEND_DEVELOPMENT: "BACKEND_DEVELOPMENT",
  FULLSTACK_DEVELOPMENT: "FULLSTACK_DEVELOPMENT",
  MOBILE_APP_DEVELOPMENT: "MOBILE_APP_DEVELOPMENT",
  DEVOPS: "DEVOPS",
  CLOUD_ENGINEERING: "CLOUD_ENGINEERING",
  SOFTWARE_ARCHITECTURE: "SOFTWARE_ARCHITECTURE",
  QUALITY_ASSURANCE: "QUALITY_ASSURANCE",
  GAME_DEVELOPMENT: "GAME_DEVELOPMENT",
});

export const TRACK_VALUES = Object.values(TRACKS);
